import React from 'react'
import { ApartmentOutlined, FileTextOutlined, ReadOutlined, TeamOutlined } from '@ant-design/icons'

export default function SystemIntro({ t }) {
  return <>
    <section id="overview" className="section system-intro"><div className="section-intro"><div className="eyebrow">ONE SYSTEM, CONNECTED CARE</div><h2>{t('医院委托，我们持续运营', 'Hospital-directed, team-operated care')}</h2><p>{t('医院提供授权和就诊资料；运营团队和院方护士负责随访与复诊跟踪，院方医生在系统里查看报告、审核随访意见。', 'The hospital provides authorization and clinical records. Our team and hospital nurses run follow-ups and visit tracking, while hospital doctors read reports and review follow-up guidance in the system.')}</p></div>
      <div className="system-ends"><article><ApartmentOutlined /><div className="system-label">HEALTH-ADMIN</div><h3>{t('医护与运营工作台', 'Clinician and operations workspace')}</h3><p>{t('运营人员、院方医生和护士各自登录：医生看报告、审核随访意见、查收结果，运营人员和护士执行随访与复诊跟踪。', 'Operators, hospital doctors and nurses each sign in: doctors read reports, review follow-up guidance and receive results; operators and nurses carry out follow-ups and visit tracking.')}</p><div className="system-tags">{[t('患者档案','Patient profiles'),t('报告记录','Clinical records'),t('医生审核','Doctor review'),t('异常与复诊','Alerts and visits'),t('运营周报','Weekly reports')].map(x => <span key={x}>{x}</span>)}</div><small>{t('本期建设重点 · 后台 MVP', 'Current focus · Operations MVP')}</small></article>
      <article className="system-patient"><TeamOutlined /><div className="system-label">HEALTH-USER</div><h3>{t('患者服务入口规划', 'Planned patient channels')}</h3><p>{t('计划通过企业微信、微信小程序、Web，连接同一服务团队。', 'Planned access to one care team through WeCom, a WeChat Mini Program and the web.')}</p><div className="system-tags"><span>{t('企业微信 · 规划中','WeCom · Planned')}</span><span>{t('小程序 · 规划中','Mini Program · Planned')}</span><span>{t('Web · 当前介绍页','Web · Introduction')}</span></div><small>{t('当前仅介绍 · 患者业务尚未开放', 'Introduction only · Patient features are not yet available')}</small></article></div>
      <p className="system-caption">{t('医院接口是主要数据来源，人工补充为辅。当前以虚构医院 Mock 联调，真实医院和微信接口尚未接通。', 'Hospital interfaces are the primary planned data source, with manual supplements. Current integration uses fictional hospital Mock data; real hospital and WeChat connections are not live.')}</p>
    </section>
    <section id="roles" className="section roles-section"><div className="section-intro"><div className="eyebrow">CLEAR RESPONSIBILITIES</div><h2>{t('医院负责医疗，我们负责服务执行', 'Clinical decisions by the hospital, service delivery by our team')}</h2></div><div className="role-grid">{[
      [t('医院','The hospital'),t('提供数据、授权与临床资源','Provide data, authorization and clinical support'),t('提供患者和就诊资料；医生登录查看报告、审核个案随访意见并处置异常，护士登录参与随访。','The hospital provides records. Doctors sign in to read reports, review patient-specific guidance and handle alerts; nurses sign in to take part in follow-ups.')],
      [t('我们 · 运营团队','Our operations team'),t('全托管服务执行','Run the managed service'),t('我们制定业务流程，核对报告、准备随访、人工联系、追踪复诊，并整理日报和周报。','We define operating procedures, check reports, prepare and perform follow-ups, track visits and produce reports.')],
      [t('医护协作','Clinical collaboration'),t('审核与查收结果','Review and receive results'),t('随访意见经责任医生在系统里审核后才联系患者；随访完成后医生查收并反馈，全过程留痕。','Follow-up guidance is used only after the responsible doctor approves it in the system; the doctor then receives the result and gives feedback, all on record.')],
    ].map(([role,title,description],i) => <article key={role}><span className="role-number">0{i+1}</span><small>{role}</small><h3>{title}</h3><p>{description}</p></article>)}</div></section>
    <section id="basis" className="basis-section"><div className="section-intro"><div className="eyebrow">THE BASIS FOR FOLLOW-UP</div><h2>{t('随访内容，要从这位患者的情况出发', 'Follow-up starts with each patient’s circumstances')}</h2><p>{t('很多随访内容根据出院报告制定，也可依据门诊、体检等原始记录。', 'Many follow-ups are based on discharge reports. Outpatient and examination records can also provide the basis.')}</p></div><div className="basis-equation">
      <article><FileTextOutlined /><small>{t('患者的个体依据','Patient-specific facts')}</small><h3>{t('出院报告 / 就诊记录','Discharge and clinical records')}</h3><ul><li>{t('出院诊断与原医嘱','Discharge diagnoses and original instructions')}</li><li>{t('注意事项与需跟进的问题','Precautions and points to follow up')}</li><li>{t('原记录用药周期、复诊日期','Recorded medication period and return-visit date')}</li></ul></article>
      <span className="basis-plus" aria-hidden="true">＋</span>
      <article><ReadOutlined /><small>{t('团队的统一流程','A consistent team workflow')}</small><h3>{t('团队业务流程（SOP）','Team operating procedures')}</h3><ul><li>{t('如何联系、如何问询','How to contact patients and ask questions')}</li><li>{t('怎样记录反馈和跟进','How to document and follow up feedback')}</li><li>{t('何时升级医生、如何协作','When to involve a doctor and how to collaborate')}</li></ul></article>
    </div><div className="basis-result"><span aria-hidden="true">↓</span><strong>{t('个体随访内容 → 医生在系统里审核 → 我们人工联系 → 医生查收结果', 'Patient-specific follow-up → Doctor review in the system → Personal contact → Doctor receives the result')}</strong><p>{t('报告提供依据，医学建议由院方医生把关。SOP 是我们如何使用系统完成业务的流程，正式版本待业务确认。', 'Clinical records provide the facts, and hospital doctors review medical guidance. SOPs describe how our team uses the system; formal procedures are awaiting confirmation.')}</p></div></section>
  </>
}
