import React from 'react'
import { ApartmentOutlined, FileTextOutlined, ReadOutlined, TeamOutlined } from '@ant-design/icons'

export default function SystemIntro({ t }) {
  return <>
    <section id="overview" className="section system-intro"><div className="section-intro"><div className="eyebrow">ONE SYSTEM, CONNECTED CARE</div><h2>{t('医院委托，我们持续运营', 'Hospital-directed, team-operated care')}</h2><p>{t('医院提供授权和就诊资料；受托运营团队负责患者服务、随访与复诊跟踪，院方负责医学判断。', 'The hospital provides authorization and clinical records. Our operations team runs follow-ups and visit tracking, while hospital clinicians make medical decisions.')}</p></div>
      <div className="system-ends"><article><ApartmentOutlined /><div className="system-label">HEALTH-ADMIN</div><h3>{t('受托运营工作台', 'Managed care operations workspace')}</h3><p>{t('由我们的运营人员使用，串联建档、随访、院方审核回执与报告交付；院方医护无需日常登录。', 'Used by our operations staff to manage records, follow-ups, hospital review evidence and reporting. Hospital clinicians do not need routine accounts.')}</p><div className="system-tags">{[t('患者档案','Patient profiles'),t('报告记录','Clinical records'),t('院方审核凭证','Hospital review evidence'),t('异常与复诊','Alerts and visits'),t('运营周报','Weekly reports')].map(x => <span key={x}>{x}</span>)}</div><small>{t('本期建设重点 · 后台 MVP', 'Current focus · Operations MVP')}</small></article>
      <article className="system-patient"><TeamOutlined /><div className="system-label">HEALTH-USER</div><h3>{t('患者服务入口规划', 'Planned patient channels')}</h3><p>{t('计划通过企业微信、微信小程序、Web，连接同一服务团队。', 'Planned access to one care team through WeCom, a WeChat Mini Program and the web.')}</p><div className="system-tags"><span>{t('企业微信 · 规划中','WeCom · Planned')}</span><span>{t('小程序 · 规划中','Mini Program · Planned')}</span><span>{t('Web · 当前介绍页','Web · Introduction')}</span></div><small>{t('当前仅介绍 · 患者业务尚未开放', 'Introduction only · Patient features are not yet available')}</small></article></div>
      <p className="system-caption">{t('医院接口是主要数据来源，人工补充为辅。当前以虚构医院 Mock 联调，真实医院和微信接口尚未接通。', 'Hospital interfaces are the primary planned data source, with manual supplements. Current integration uses fictional hospital Mock data; real hospital and WeChat connections are not live.')}</p>
    </section>
    <section id="roles" className="section roles-section"><div className="section-intro"><div className="eyebrow">CLEAR RESPONSIBILITIES</div><h2>{t('医院负责医疗，我们负责服务执行', 'Clinical decisions by the hospital, service delivery by our team')}</h2></div><div className="role-grid">{[
      [t('医院','The hospital'),t('提供数据、授权与临床资源','Provide data, authorization and clinical support'),t('提供患者和就诊资料，医生审核个案建议并处理需要医学判断的问题；医护可接收服务报告。','The hospital provides records and clinical contacts. Doctors review patient-specific guidance and handle medical decisions; staff can receive service reports.')],
      [t('我们 · 运营团队','Our operations team'),t('全托管服务执行','Run the managed service'),t('我们制定业务流程，核对报告、准备随访、人工联系、追踪复诊，并整理日报和周报。','We define operating procedures, check reports, prepare and perform follow-ups, track visits and produce reports.')],
      [t('院方协作','Hospital collaboration'),t('审核与接收结果','Review and receive results'),t('需要医学判断时向院方取得意见；运营人员登记实际审核与交接凭证，医生和护士无需后台账号。','Our team obtains clinical decisions when needed and records actual review and handover evidence. Hospital doctors and nurses do not need workspace accounts.')],
    ].map(([role,title,description],i) => <article key={role}><span className="role-number">0{i+1}</span><small>{role}</small><h3>{title}</h3><p>{description}</p></article>)}</div></section>
    <section id="basis" className="basis-section"><div className="section-intro"><div className="eyebrow">THE BASIS FOR FOLLOW-UP</div><h2>{t('随访内容，要从这位患者的情况出发', 'Follow-up starts with each patient’s circumstances')}</h2><p>{t('很多随访内容根据出院报告制定，也可依据门诊、体检等原始记录。', 'Many follow-ups are based on discharge reports. Outpatient and examination records can also provide the basis.')}</p></div><div className="basis-equation">
      <article><FileTextOutlined /><small>{t('患者的个体依据','Patient-specific facts')}</small><h3>{t('出院报告 / 就诊记录','Discharge and clinical records')}</h3><ul><li>{t('出院诊断与原医嘱','Discharge diagnoses and original instructions')}</li><li>{t('注意事项与需跟进的问题','Precautions and points to follow up')}</li><li>{t('原记录用药周期、复诊日期','Recorded medication period and return-visit date')}</li></ul></article>
      <span className="basis-plus" aria-hidden="true">＋</span>
      <article><ReadOutlined /><small>{t('团队的统一流程','A consistent team workflow')}</small><h3>{t('团队业务流程（SOP）','Team operating procedures')}</h3><ul><li>{t('如何联系、如何问询','How to contact patients and ask questions')}</li><li>{t('怎样记录反馈和跟进','How to document and follow up feedback')}</li><li>{t('何时升级医生、如何协作','When to involve a doctor and how to collaborate')}</li></ul></article>
    </div><div className="basis-result"><span aria-hidden="true">↓</span><strong>{t('个体随访内容 → 院方审核 → 登记回执 → 我们人工联系', 'Patient-specific follow-up → Hospital review → Evidence → Personal contact')}</strong><p>{t('报告提供依据，医学建议由院方医生把关。SOP 是我们如何使用系统完成业务的流程，正式版本待业务确认。', 'Clinical records provide the facts, and hospital doctors review medical guidance. SOPs describe how our team uses the system; formal procedures are awaiting confirmation.')}</p></div></section>
  </>
}
