import React from 'react'
import { ApartmentOutlined, FileTextOutlined, ReadOutlined, TeamOutlined } from '@ant-design/icons'

export default function SystemIntro({ t }) {
  return <>
    <section id="overview" className="section system-intro"><div className="section-intro"><div className="eyebrow">ONE SYSTEM, CONNECTED CARE</div><h2>{t('一个系统，连接团队与患者', 'One system connecting teams and patients')}</h2><p>{t('BGSSAI Health 是医患运营管理系统：让患者档案、随访、异常和复诊都有明确的负责人。', 'BGSSAI Health manages patient relationships and care operations, with clear responsibility for records, follow-ups, alerts and return visits.')}</p></div>
      <div className="system-ends"><article><ApartmentOutlined /><div className="system-label">HEALTH-ADMIN</div><h3>{t('团队协作与运营管理', 'The care team workspace')}</h3><p>{t('给运营团队、医生和健康管家使用，串联从建档到复诊的工作。', 'For operations staff, doctors and care coordinators, connecting the work from patient records to return visits.')}</p><div className="system-tags">{[t('患者档案','Patient profiles'),t('报告记录','Clinical records'),t('随访审核','Follow-up review'),t('异常与复诊','Alerts and visits'),t('运营周报','Weekly reports')].map(x => <span key={x}>{x}</span>)}</div><small>{t('本期建设重点 · 后台 MVP', 'Current focus · Staff MVP')}</small></article>
      <article className="system-patient"><TeamOutlined /><div className="system-label">HEALTH-USER</div><h3>{t('患者服务入口规划', 'Planned patient channels')}</h3><p>{t('计划通过企业微信、微信小程序、Web，连接同一服务团队。', 'Planned access to one care team through WeCom, a WeChat Mini Program and the web.')}</p><div className="system-tags"><span>{t('企业微信 · 规划中','WeCom · Planned')}</span><span>{t('小程序 · 规划中','Mini Program · Planned')}</span><span>{t('Web · 当前介绍页','Web · Introduction')}</span></div><small>{t('当前仅介绍 · 患者业务尚未开放', 'Introduction only · Patient features are not yet available')}</small></article></div>
      <p className="system-caption">{t('医院接口是主要数据来源，人工补充为辅。当前以虚构医院 Mock 联调，真实医院和微信接口尚未接通。', 'Hospital interfaces are the primary planned data source, with manual supplements. Current integration uses fictional hospital Mock data; real hospital and WeChat connections are not live.')}</p>
    </section>
    <section id="roles" className="section roles-section"><div className="section-intro"><div className="eyebrow">CLEAR RESPONSIBILITIES</div><h2>{t('一支团队，各自有明确的职责', 'One team, with clear responsibilities')}</h2></div><div className="role-grid">{[
      [t('我们 · 运营团队','Our operations team'),t('制定 SOP，培训医生','Define SOPs and train doctors'),t('制定、发布服务 SOP，给医生培训服务流程，组织任务执行与运营复盘。','Define and publish service SOPs, train doctors in the workflow, and coordinate delivery and operational reviews.')],
      [t('医生','Doctors'),t('按流程协作，负责医学判断','Collaborate and provide clinical judgment'),t('接受 SOP 培训、按流程协作，审核患者个案建议，处理需要医学判断的问题。','Follow the trained SOP workflow, review patient-specific guidance and handle questions that require clinical judgment.')],
      [t('健康管家 / 护理团队','Care coordinators and nurses'),t('落实随访，持续跟进','Carry out and follow up care'),t('核对报告、准备随访、按审核内容人工联系，记录反馈并升级异常。','Check reports, prepare follow-ups, contact patients with reviewed guidance, record feedback and escalate concerns.')],
    ].map(([role,title,description],i) => <article key={role}><span className="role-number">0{i+1}</span><small>{role}</small><h3>{title}</h3><p>{description}</p></article>)}</div></section>
    <section id="basis" className="basis-section"><div className="section-intro"><div className="eyebrow">THE BASIS FOR FOLLOW-UP</div><h2>{t('随访内容，要从这位患者的情况出发', 'Follow-up starts with each patient’s circumstances')}</h2><p>{t('很多随访内容根据出院报告制定，也可依据门诊、体检等原始记录。', 'Many follow-ups are based on discharge reports. Outpatient and examination records can also provide the basis.')}</p></div><div className="basis-equation">
      <article><FileTextOutlined /><small>{t('患者的个体依据','Patient-specific facts')}</small><h3>{t('出院报告 / 就诊记录','Discharge and clinical records')}</h3><ul><li>{t('出院诊断与原医嘱','Discharge diagnoses and original instructions')}</li><li>{t('注意事项与需跟进的问题','Precautions and points to follow up')}</li><li>{t('原记录用药周期、复诊日期','Recorded medication period and return-visit date')}</li></ul></article>
      <span className="basis-plus" aria-hidden="true">＋</span>
      <article><ReadOutlined /><small>{t('团队的统一流程','A consistent team workflow')}</small><h3>{t('我们制定的服务 SOP','Service SOPs defined by our team')}</h3><ul><li>{t('如何联系、如何问询','How to contact patients and ask questions')}</li><li>{t('怎样记录反馈和跟进','How to document and follow up feedback')}</li><li>{t('何时升级医生、如何协作','When to involve a doctor and how to collaborate')}</li></ul></article>
    </div><div className="basis-result"><span aria-hidden="true">↓</span><strong>{t('个体随访内容 → 医生审核 → 团队人工联系', 'Patient-specific follow-up → Doctor review → Personal contact')}</strong><p>{t('报告提供依据，SOP 规范流程；具体建议由责任医生审核。', 'Reports provide the facts, SOPs structure the work, and the responsible doctor reviews individual guidance.')}</p></div></section>
  </>
}
