// Behavioral regression checks against the implemented workflow, using fictional state.
const assert=require('node:assert/strict'),harness=require('./prototype-harness.cjs');
const {run,elements}=harness();
const act=(kind,id,data={})=>{run(`journeyAction(${JSON.stringify(kind)},${JSON.stringify(id)},{version:journeyState().find(j=>j.id===${Number(String(id).split(':')[0])})?.version,evidence:'虚构依据',occurred_at:'2026-10-02T10:00',...${JSON.stringify(data)}})`)};
const role=id=>run(`account=person(${id})`);
const create=(patient,kind,event,phase='FULL')=>act('journey-create',0,{patient:String(patient),kind,event_key:event,entry_phase:phase,source_system:'MANUAL',event_at:'2026-10-01T09:00',identity_evidence:'虚构身份核验',handoff_evidence:'虚构服务交接'});
const node={seq:1,stage:'CUSTOM',offset_days:3,task_type:'FOLLOWUP',priority:'P2',title:'本事件随访',checklist:'虚构原医嘱核验'};
const draft=id=>act('journey-plan-draft',id,{plan_text:'虚构个案计划',nodes:JSON.stringify([node])});
const stage=id=>run(`journeyStep(journeyState().find(j=>j.id===${id}))`);
role(1);create(1002,'OUTPATIENT','VISIT-1');assert.equal(run('journeyState()[0].status'),'INTAKE');
act('journey-handoff',1);assert.equal(stage(1),'HANDOFF','manager cannot impersonate current owner');
role(3);act('journey-handoff',1,{request_id:'accept-once'});assert.equal(stage(1),'CONSULT');
const history=run('journeyState()[0].logs.length');act('journey-handoff',1,{request_id:'accept-once',version:0});assert.equal(run('journeyState()[0].logs.length'),history);
act('journey-step',1,{version:0});assert.equal(stage(1),'CONSULT','stale version rejected');
act('journey-step',1);assert.equal(stage(1),'ARRIVAL');
act('journey-step',1,{appointment_id:7001});assert.equal(stage(1),'ARRIVAL');
run("demo.appointments.push({id:7702,patient:1002,status:'ARRIVED',appointment_type:'OUTPATIENT',arrived_at:'2026-10-01T09:30'})");
act('journey-step',1,{appointment_id:7702});act('journey-step',1);assert.equal(stage(1),'CLINICAL');
act('journey-step',1,{record_id:102});assert.equal(stage(1),'CLINICAL','nurse cannot sign report');
role(6);act('journey-step',1,{record_id:102});assert.equal(stage(1),'CLINICAL','another doctor cannot sign');
role(2);act('journey-step',1,{record_id:102});assert.equal(stage(1),'PLAN');
role(3);draft(1);assert.equal(run('journeyState()[0].plans[0].status'),'DRAFT');
act('journey-plan-review',1,{approved:'true',review_note:'冒充医生'});assert.equal(stage(1),'PLAN');
role(2);act('journey-plan-review',1,{approved:'false',review_note:'请修改'});assert.equal(run('journeyState()[0].plans[0].tasks.length'),0);
role(3);draft(1);role(2);act('journey-plan-review',1,{approved:'true',review_note:'本人审核通过'});assert.equal(stage(1),'FOLLOWUP');
role(3);act('journey-step',1);assert.equal(stage(1),'FOLLOWUP');
run("const t1=demo.tasks.find(t=>t.journey_id===1);t1.status='COMPLETED';t1.received=true;t1.receiver=6");
act('journey-step',1);assert.equal(stage(1),'FOLLOWUP','wrong doctor receipt rejected');
run('t1.receiver=2');act('journey-step',1);assert.equal(stage(1),'CLOSE');
act('journey-step',1,{outcome:'EXIT',satisfaction_status:'NOT_INVITED'});assert.equal(stage(1),'CLOSE','exit is not closure');
act('journey-step',1,{outcome:'NONE',satisfaction_status:'NOT_INVITED'});assert.equal(stage(1),'CLOSE');
role(2);act('journey-no-revisit',1,{reason:'虚构本次医学依据'});role(3);
act('journey-case-open',1,{kind:'CLINICAL',summary:'虚构临床异常',due_at:'2026-10-01T11:00'});
act('journey-step',1,{outcome:'NONE',satisfaction_status:'NOT_INVITED'});assert.equal(stage(1),'CLOSE');
act('journey-case-action',1,{case_id:1,action:'RESOLVE'});assert.equal(run('journeyState()[0].cases[0].status'),'OPEN');
role(2);act('journey-case-action',1,{case_id:1,action:'ACCEPT'});act('journey-case-action',1,{case_id:1,action:'RESOLVE'});
act('journey-case-action',1,{case_id:1,action:'CLOSE'});assert.equal(run('journeyState()[0].cases[0].status'),'RESOLVED');
role(3);act('journey-case-action',1,{case_id:1,action:'CLOSE'});
act('journey-step',1,{outcome:'NONE',satisfaction_status:'RATED',satisfaction_score:''});assert.equal(stage(1),'CLOSE');
act('journey-step',1,{outcome:'NONE',satisfaction_status:'NO_RESPONSE',satisfaction_score:5});assert.equal(stage(1),'CLOSE');
act('journey-step',1,{outcome:'NONE',satisfaction_status:'NO_RESPONSE'});assert.equal(run('journeyState()[0].status'),'CLOSED');assert.equal(run('journeyState()[0].satisfaction.score'),null);
const closedLogs=run('journeyState()[0].logs.length');act('journey-step',1);assert.equal(run('journeyState()[0].logs.length'),closedLogs);
// Discharge FULL path requires current-owner discharge handoff.
role(4);create(1001,'DISCHARGE','DISCHARGE-1');act('journey-handoff',2);act('journey-step',2);assert.equal(stage(2),'CLINICAL');
role(2);run("demo.records[0].status='READ';demo.records[0].viewer=2");act('journey-step',2,{record_id:101});assert.equal(stage(2),'DISCHARGE_HANDOFF');
role(1);act('journey-step',2);assert.equal(stage(2),'DISCHARGE_HANDOFF');role(4);act('journey-step',2);draft(2);role(2);act('journey-plan-review',2,{approved:'true',review_note:'虚构审核'});role(4);
act('journey-status',2,{action:'PAUSE'});assert.equal(run('journeyTaskAllowed(demo.tasks.find(t=>t.journey_id===2))'),false);
act('journey-status',2,{action:'RESUME'});draft(2);assert.equal(run('demo.tasks.find(t=>t.journey_id===2).status'),'CANCELLED');assert.equal(run('journeyState()[1].plans[0].status'),'SUPERSEDED');
role(2);act('journey-plan-review',2,{approved:'true',review_note:'替换审核'});role(4);
run("const t2=demo.tasks.filter(t=>t.journey_id===2).at(-1);t2.status='COMPLETED';t2.received=true;t2.receiver=2;demo.alerts.forEach(a=>a.status='CLOSED')");
act('journey-step',2);assert.equal(stage(2),'CLOSE');
run("demo.appointments.push({id:7703,patient:1001,status:'COMPLETED',appointment_type:'REVISIT',arrived_at:'2026-10-02T09:00',outcome:'虚构复诊诊疗结果'})");
act('journey-step',2,{outcome:'VERIFIED',appointment_id:7703,satisfaction_status:'RATED',satisfaction_score:4});assert.equal(run('journeyState()[1].status'),'CLOSED');
// Direct after-care intake, source-wide duplicate, reassignment, withdrawal across events.
create(1001,'DISCHARGE','DISCHARGE-2','AFTER_CARE');create(1001,'DISCHARGE','DISCHARGE-2','AFTER_CARE');assert.equal(run('journeyState().length'),3);
act('journey-handoff',3);assert.equal(stage(3),'CLINICAL');assert.equal(run('journeyState()[2].skipped.length'),1);
act('journey-step',3,{record_id:101});assert.equal(stage(3),'CLINICAL','report cannot be reused across events');
create(1001,'DISCHARGE','DISCHARGE-3','AFTER_CARE');act('journey-handoff',4);
act('journey-case-open',3,{kind:'CLINICAL',summary:'撤回后保留安全事项',due_at:'2026-10-01T11:00'});
act('journey-status',3,{action:'WITHDRAW'});assert.equal(run('journeyState()[2].status'),'EXITED');assert.equal(run('journeyState()[3].status'),'EXITED');assert.equal(run('patient(1001).service_consent'),false);
role(2);act('journey-case-action',3,{case_id:1,action:'ACCEPT'});act('journey-case-action',3,{case_id:1,action:'RESOLVE'});role(4);act('journey-case-action',3,{case_id:1,action:'CLOSE'});assert.equal(run('journeyState()[2].cases[0].status'),'CLOSED');
console.log('Implemented journey workflow passed: both complete paths, direct intake, responsible roles, stale versions/retries, report/arrival evidence, plan rejection/replacement, linked tasks and doctor receipt, cases, satisfaction, exit and withdrawal.');
