package com.boruikang.health.model;
import java.time.LocalDate;
import java.time.LocalDateTime;
public class Patient extends BaseRow {
    public Long hospitalId;
    public Long accountId;
    public String sourceSystem;
    public String hospitalPatientId;
    public String name;
    public String gender;
    public Integer age;
    public String phone;
    public String department;
    public String disease;
    public String riskLevel;
    public String lifecycle;
    public Long doctorId;
    public Long ownerId;
    public Long channelId;
    public Long servicePackageId;
    public LocalDateTime consentAt;
    public String note;
    public Integer version;
    public String idCard;
    public LocalDate birthDate;
    public String address;
    public String emergencyContact;
    public String emergencyPhone;
    public String inpatientNo;
    public String bedNo;
    public String patientType;
    public String sourceScene;
    public Long orgId;
    public Long referrerId;
    public LocalDateTime lastContactAt;
    public LocalDateTime lostSince;
    public String consentVersion;
    public String consentEvidence;
    public String tags;
}
