-- HEALTH-MVP-1 / MySQL 8. Canonical schema, non-destructive initialization.
CREATE TABLE IF NOT EXISTS health_account (
 id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
 username VARCHAR(64) NOT NULL, password VARCHAR(200) NOT NULL, real_name VARCHAR(80) NOT NULL,
 role_code VARCHAR(32) NOT NULL, hospital_id BIGINT NOT NULL, current_session_id VARCHAR(64) DEFAULT NULL, is_enabled TINYINT(1) NOT NULL DEFAULT 1,
 del_flag TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除字段', creator VARCHAR(64) DEFAULT NULL, modifier VARCHAR(64) DEFAULT NULL,
 gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, gmt_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (id), UNIQUE KEY uk_account_username (username)
);
CREATE TABLE IF NOT EXISTS patient (
 id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键', hospital_id BIGINT NOT NULL, account_id BIGINT DEFAULT NULL,
 source_system VARCHAR(24) NOT NULL DEFAULT 'MANUAL', hospital_patient_id VARCHAR(120) DEFAULT NULL,
 name VARCHAR(80) NOT NULL, gender VARCHAR(16) NOT NULL, age INT NOT NULL, phone VARCHAR(24) NOT NULL,
 department VARCHAR(80) NOT NULL, disease VARCHAR(120) NOT NULL, risk_level VARCHAR(16) NOT NULL DEFAULT 'UNKNOWN', lifecycle VARCHAR(20) NOT NULL DEFAULT 'ENROLLED',
 doctor_id BIGINT DEFAULT NULL, owner_id BIGINT DEFAULT NULL, channel_id BIGINT DEFAULT NULL, service_package_id BIGINT DEFAULT NULL,
 consent_at DATETIME DEFAULT NULL, note VARCHAR(2000) DEFAULT NULL, version INT NOT NULL DEFAULT 0,
 del_flag TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除字段', creator VARCHAR(64) DEFAULT NULL, modifier VARCHAR(64) DEFAULT NULL,
 gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, gmt_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (id), UNIQUE KEY uk_patient_account (account_id), UNIQUE KEY uk_patient_source (hospital_id, source_system, hospital_patient_id), KEY idx_patient_scope (hospital_id, doctor_id, owner_id), KEY idx_patient_risk (hospital_id, risk_level)
);
CREATE TABLE IF NOT EXISTS care_task (
 id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键', hospital_id BIGINT NOT NULL, patient_id BIGINT NOT NULL,
 task_type VARCHAR(24) NOT NULL, title VARCHAR(160) NOT NULL, priority VARCHAR(4) NOT NULL, status VARCHAR(24) NOT NULL,
 assignee_id BIGINT DEFAULT NULL, doctor_id BIGINT DEFAULT NULL, due_at DATETIME NOT NULL,
 record_id BIGINT DEFAULT NULL, sop_id BIGINT DEFAULT NULL, draft_text TEXT, draft_origin VARCHAR(16) DEFAULT NULL,
 approved_text TEXT, review_note VARCHAR(2000) DEFAULT NULL, reviewer_id BIGINT DEFAULT NULL, reviewed_at DATETIME DEFAULT NULL,
 completed_at DATETIME DEFAULT NULL, outcome VARCHAR(2000) DEFAULT NULL, evidence VARCHAR(1000) DEFAULT NULL,
 followup_stage VARCHAR(24) DEFAULT NULL,
 next_contact_at DATETIME DEFAULT NULL,
 contact_result VARCHAR(24) DEFAULT NULL,
 identity_verified TINYINT(1) NOT NULL DEFAULT 0,
 handover_status VARCHAR(24) DEFAULT NULL,
 doctor_feedback VARCHAR(2000) DEFAULT NULL,
 acknowledged_at DATETIME DEFAULT NULL,
 request_key VARCHAR(80) NOT NULL, version INT NOT NULL DEFAULT 0,
 del_flag TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除字段', creator VARCHAR(64) DEFAULT NULL, modifier VARCHAR(64) DEFAULT NULL,
 gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, gmt_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (id), UNIQUE KEY uk_task_request (hospital_id, request_key), KEY idx_task_patient (hospital_id, patient_id), KEY idx_task_queue (hospital_id, task_type, status, due_at)
);
CREATE TABLE IF NOT EXISTS care_record (
 id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键', hospital_id BIGINT NOT NULL, patient_id BIGINT NOT NULL,
 record_type VARCHAR(24) NOT NULL, occurred_at DATETIME NOT NULL, content TEXT,
 medication_cycle_days INT DEFAULT NULL, next_visit_date DATE DEFAULT NULL,
 systolic DECIMAL(7,2) DEFAULT NULL, diastolic DECIMAL(7,2) DEFAULT NULL, heart_rate DECIMAL(7,2) DEFAULT NULL,
 weight DECIMAL(7,2) DEFAULT NULL, glucose DECIMAL(7,2) DEFAULT NULL, is_needs_contact TINYINT(1) NOT NULL DEFAULT 0,
 source_system VARCHAR(24) NOT NULL, external_id VARCHAR(120) DEFAULT NULL,
 del_flag TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除字段', creator VARCHAR(64) DEFAULT NULL, modifier VARCHAR(64) DEFAULT NULL,
 gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, gmt_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (id), KEY idx_record_patient (hospital_id, patient_id, occurred_at), UNIQUE KEY uk_record_source (hospital_id, source_system, external_id)
);
CREATE TABLE IF NOT EXISTS care_message (
 id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键', hospital_id BIGINT NOT NULL, patient_id BIGINT NOT NULL, task_id BIGINT DEFAULT NULL,
 sender_id BIGINT NOT NULL, sender_role VARCHAR(24) NOT NULL, direction VARCHAR(24) NOT NULL, content TEXT NOT NULL,
 del_flag TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除字段', creator VARCHAR(64) DEFAULT NULL, modifier VARCHAR(64) DEFAULT NULL,
 gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, gmt_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (id), KEY idx_message_patient (hospital_id, patient_id, gmt_create), UNIQUE KEY uk_message_task (task_id, direction)
);
CREATE TABLE IF NOT EXISTS knowledge_entry (
 id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键', hospital_id BIGINT NOT NULL, kind VARCHAR(24) NOT NULL,
 department VARCHAR(80) NOT NULL, title VARCHAR(160) NOT NULL, content TEXT NOT NULL, source VARCHAR(300) NOT NULL,
 version INT NOT NULL DEFAULT 1, status VARCHAR(16) NOT NULL DEFAULT 'DRAFT', reviewer_id BIGINT DEFAULT NULL, reviewed_at DATETIME DEFAULT NULL,
 service_days INT DEFAULT NULL, followup_count INT DEFAULT NULL,
 del_flag TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除字段', creator VARCHAR(64) DEFAULT NULL, modifier VARCHAR(64) DEFAULT NULL,
 gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, gmt_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (id), KEY idx_knowledge_scope (hospital_id, kind, status)
);
CREATE TABLE IF NOT EXISTS intake_channel (
 id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键', hospital_id BIGINT NOT NULL, title VARCHAR(120) NOT NULL,
 source VARCHAR(24) NOT NULL, department VARCHAR(80) NOT NULL, doctor_id BIGINT DEFAULT NULL, owner_id BIGINT DEFAULT NULL,
 token VARCHAR(64) NOT NULL, is_active TINYINT(1) NOT NULL DEFAULT 1,
 del_flag TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除字段', creator VARCHAR(64) DEFAULT NULL, modifier VARCHAR(64) DEFAULT NULL,
 gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, gmt_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (id), UNIQUE KEY uk_channel_token (token)
);
CREATE TABLE IF NOT EXISTS audit_event (
 id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键', hospital_id BIGINT NOT NULL, patient_id BIGINT DEFAULT NULL,
 actor_id BIGINT NOT NULL, action VARCHAR(64) NOT NULL, resource_id BIGINT DEFAULT NULL,
 before_state VARCHAR(32) DEFAULT NULL, after_state VARCHAR(32) DEFAULT NULL, detail VARCHAR(500) DEFAULT NULL,
 del_flag TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除字段', creator VARCHAR(64) DEFAULT NULL, modifier VARCHAR(64) DEFAULT NULL,
 gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, gmt_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (id), KEY idx_audit_patient (hospital_id, patient_id, gmt_create)
);
CREATE TABLE IF NOT EXISTS integration_config (
 id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键', hospital_id BIGINT NOT NULL, provider VARCHAR(24) NOT NULL,
 endpoint VARCHAR(300) NOT NULL, model_name VARCHAR(120) NOT NULL, secret VARCHAR(2000) DEFAULT NULL, is_enabled TINYINT(1) NOT NULL DEFAULT 0,
 del_flag TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除字段', creator VARCHAR(64) DEFAULT NULL, modifier VARCHAR(64) DEFAULT NULL,
 gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, gmt_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (id), UNIQUE KEY uk_integration_provider (hospital_id, provider)
);

-- Non-destructive local upgrade for workspaces created before hospital Mock integration.
ALTER TABLE patient ADD COLUMN IF NOT EXISTS source_system VARCHAR(24) NOT NULL DEFAULT 'MANUAL';
ALTER TABLE patient ADD COLUMN IF NOT EXISTS hospital_patient_id VARCHAR(120) DEFAULT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uk_patient_source ON patient(hospital_id, source_system, hospital_patient_id);

CREATE TABLE IF NOT EXISTS contact_attempt (
 id BIGINT NOT NULL AUTO_INCREMENT, hospital_id BIGINT NOT NULL, patient_id BIGINT NOT NULL, task_id BIGINT NOT NULL, actor_id BIGINT NOT NULL,
 contact_at DATETIME NOT NULL, method VARCHAR(20) NOT NULL, result VARCHAR(24) NOT NULL,
 identity_verified TINYINT(1) NOT NULL DEFAULT 0, report_reviewed TINYINT(1) NOT NULL DEFAULT 0, recipient_role VARCHAR(24) DEFAULT NULL,
 reason VARCHAR(1000) DEFAULT NULL, next_contact_at DATETIME DEFAULT NULL, next_plan VARCHAR(1000) DEFAULT NULL,
 medication_feedback VARCHAR(2000) DEFAULT NULL, patient_questions VARCHAR(2000) DEFAULT NULL, evidence VARCHAR(1000) NOT NULL,
 request_key VARCHAR(80) NOT NULL,
 del_flag TINYINT(1) NOT NULL DEFAULT 0, creator VARCHAR(64) DEFAULT NULL, modifier VARCHAR(64) DEFAULT NULL,
 gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, gmt_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (id), UNIQUE KEY uk_contact_request(hospital_id,request_key), KEY idx_contact_task(hospital_id,task_id,contact_at)
);
CREATE TABLE IF NOT EXISTS operations_report (
 id BIGINT NOT NULL AUTO_INCREMENT, hospital_id BIGINT NOT NULL, owner_id BIGINT NOT NULL, report_type VARCHAR(16) NOT NULL,
 from_date DATE NOT NULL, to_date DATE NOT NULL, summary VARCHAR(2000) NOT NULL, action_plan VARCHAR(2000) NOT NULL, snapshot_json TEXT NOT NULL,
 delivery_evidence VARCHAR(1000) DEFAULT NULL, delivered_at DATETIME DEFAULT NULL, version INT NOT NULL DEFAULT 0,
 del_flag TINYINT(1) NOT NULL DEFAULT 0, creator VARCHAR(64) DEFAULT NULL, modifier VARCHAR(64) DEFAULT NULL,
 gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, gmt_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (id), KEY idx_ops_report(hospital_id,owner_id,report_type,from_date)
);

ALTER TABLE care_task ADD COLUMN IF NOT EXISTS followup_stage VARCHAR(24) DEFAULT NULL;
ALTER TABLE care_task ADD COLUMN IF NOT EXISTS next_contact_at DATETIME DEFAULT NULL;
ALTER TABLE care_task ADD COLUMN IF NOT EXISTS contact_result VARCHAR(24) DEFAULT NULL;
ALTER TABLE care_task ADD COLUMN IF NOT EXISTS identity_verified TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE care_task ADD COLUMN IF NOT EXISTS handover_status VARCHAR(24) DEFAULT NULL;
ALTER TABLE care_task ADD COLUMN IF NOT EXISTS doctor_feedback VARCHAR(2000) DEFAULT NULL;
ALTER TABLE care_task ADD COLUMN IF NOT EXISTS acknowledged_at DATETIME DEFAULT NULL;

UPDATE knowledge_entry SET kind='EDUCATION',status='DRAFT',reviewer_id=NULL,reviewed_at=NULL WHERE kind='SOP';
