-- Reference service content only. The demo approval is not a hospital clinical approval.
INSERT INTO knowledge_entry (id,hospital_id,kind,department,title,content,source,version,status,reviewer_id,reviewed_at,creator) VALUES (1,1,'EDUCATION','全科','首次联系与出院随访（演示）','1. 核对是否为本人或授权联系人，并确认现在方便沟通。
2. 了解近期身体感受，有无新的不适或希望医生处理的问题。
3. 核对是否按原医嘱执行，记录遇到的困难；不自行给出调药建议。
4. 核对原记录中的复诊日期与安排。
5. 总结本次反馈、下一步联系计划，并把需要医学判断的问题交给医生。','问询内容参考草稿；无正式 SOP，个体建议另由责任医生审核',1,'DRAFT',NULL,NULL,'demo-seed') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO knowledge_entry (id,hospital_id,kind,department,title,content,source,version,status,reviewer_id,reviewed_at,creator) VALUES (2,1,'EDUCATION','心血管内科','心血管患者信息核对（演示）','请核对最近一次就诊时间、医生安排与复诊日期。请问近期身体感受与之前相比是否有变化？是否有需要医生解答的问题？如已测量血压、心率或体重，可提供测量时间与数值。请说明按原医嘱执行时遇到的困难。记录信息后提交责任医生判断，不根据本问卷自行诊断或调药。','信息采集参考草稿；不含临床阈值或可执行规则',1,'DRAFT',NULL,NULL,'demo-seed') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO knowledge_entry (id,hospital_id,kind,department,title,content,source,version,status,reviewer_id,reviewed_at,service_days,followup_count,creator) VALUES (3,1,'PACKAGE','全科','连续健康服务基础包（演示）','提供健康档案、服务咨询、指标记录、4次计划随访与复诊协调。具体服务范围、时间及费用以医院确认的服务说明为准。本演示不含诊断、处方或线上支付。','参考健康管理服务包汇总；不照搬医院价格与承诺',1,'PUBLISHED',2,CURRENT_TIMESTAMP,365,4,'demo-seed') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO knowledge_entry (id,hospital_id,kind,department,title,content,source,version,status,creator) VALUES (4,1,'EDUCATION','全科','复诊前的资料准备','请按医院要求携带就诊资料、近期检查报告和目前正在使用的药物信息。就诊地点、时间和具体准备要求请向医院服务团队核实。','通用服务流程草稿，等待本院医生审核',1,'DRAFT','demo-seed') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO integration_config (id,hospital_id,provider,endpoint,model_name,secret,is_enabled,creator) VALUES (1,1,'AI','https://api.deepseek.com/chat/completions','deepseek-flash','',0,'seed') ON DUPLICATE KEY UPDATE id=id;
-- BEGIN OPERATIONS LEDGER 1.5
-- Message templates and SLA defaults (fictional demo content; wording adapted from generic follow-up scripts, no hospital names).
INSERT INTO message_template (id,hospital_id,code,channel,scene,title,content,is_active,version,creator) VALUES (1,1,'SMS_FIRST_CONTACT','SMS','FIRST_CONTACT','首次联系短信','您好，我是{医院}健康管理团队{姓名}。您近期的{检查}结果建议由专科医生进一步评估，我们将于{时间}致电与您沟通，请留意来电。回复TD退订。',1,0,'demo-seed') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO message_template (id,hospital_id,code,channel,scene,title,content,is_active,version,creator) VALUES (2,1,'SMS_HIGH_RISK','SMS','HIGH_RISK','高风险提醒短信','您好，{医院}健康管理团队提醒：您的{检查}结果提示需尽快到院复核，已为您预留{日期}{科室}号源，请携带既往资料按时到院。如需改期请回电{电话}。',1,0,'demo-seed') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO message_template (id,hospital_id,code,channel,scene,title,content,is_active,version,creator) VALUES (3,1,'SMS_ARRIVAL_REMINDER','SMS','ARRIVAL_REMINDER','到诊提醒短信','温馨提醒：您预约的{日期}{时间}{科室}就诊即将到期，请携带身份证、既往检查报告及在用药物到{地点}报到。如有变动请回电{电话}。',1,0,'demo-seed') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO message_template (id,hospital_id,code,channel,scene,title,content,is_active,version,creator) VALUES (4,1,'SMS_FOLLOWUP_REMINDER','SMS','FOLLOWUP_REMINDER','随访提醒短信','您好，{医院}健康管理团队将于{日期}对您进行例行随访，请准备近期血压、心率等自测记录。如时间不便请回复调整。',1,0,'demo-seed') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO message_template (id,hospital_id,code,channel,scene,title,content,is_active,version,creator) VALUES (5,1,'SMS_REVISIT_REMINDER','SMS','REVISIT_REMINDER','复诊提醒短信','您好，根据医生安排您需于{日期}前复诊复查。如尚未预约，可回电{电话}由我们协助安排。',1,0,'demo-seed') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO message_template (id,hospital_id,code,channel,scene,title,content,is_active,version,creator) VALUES (6,1,'SMS_NO_SHOW','SMS','NO_SHOW','未到院跟进短信','您好，未见您于{日期}到院就诊。若因故未能前来，可回电{电话}重新安排，团队将协助您完成检查。',1,0,'demo-seed') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO message_template (id,hospital_id,code,channel,scene,title,content,is_active,version,creator) VALUES (7,1,'SCRIPT_FIRST_CONTACT','SCRIPT','FIRST_CONTACT','首次电话话术','1 核实身份：请问是{姓名}本人或家属吗？2 说明来意：我是{医院}健康管理团队，因为您{日期}的{检查}结果需要专科评估。3 了解现状：最近有无不适、是否已就诊。4 邀约：建议{日期}前到{科室}复核，我们可协助预约。5 记录：意愿、到院方式、下次联系时间。',1,0,'demo-seed') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO message_template (id,hospital_id,code,channel,scene,title,content,is_active,version,creator) VALUES (8,1,'SCRIPT_HIGH_RISK','SCRIPT','HIGH_RISK','高风险邀约话术','强调结果提示需要医生尽快复核，说明绿色通道与已预留号源；询问是否需要家属陪同；明确到院时间和地点；如患者犹豫，记录顾虑并约定 24 小时内再联系；任何医学判断转交医生。',1,0,'demo-seed') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO message_template (id,hospital_id,code,channel,scene,title,content,is_active,version,creator) VALUES (9,1,'SCRIPT_FAMILY','SCRIPT','FAMILY','家属接听话术','确认家属身份与患者关系；说明联系目的但不透露具体诊断细节；请家属转告并约定患者本人方便的回电时间；记录家属联系方式作为备用。',1,0,'demo-seed') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO message_template (id,hospital_id,code,channel,scene,title,content,is_active,version,creator) VALUES (10,1,'SCRIPT_HESITANT','SCRIPT','HESITANT','犹豫患者话术','倾听顾虑（费用、路程、时间、担心结果）；对应说明检查项目与大致费用、可预约时间段、家属陪同；不做承诺、不夸大病情；约定再次联系时间。',1,0,'demo-seed') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO message_template (id,hospital_id,code,channel,scene,title,content,is_active,version,creator) VALUES (11,1,'SCRIPT_REFUSED','SCRIPT','REFUSED','拒绝患者话术','尊重患者选择，简要说明风险由医生判断，留下团队电话；记录拒绝原因；按 SLA 安排一次后续关怀联系，不重复骚扰。',1,0,'demo-seed') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO message_template (id,hospital_id,code,channel,scene,title,content,is_active,version,creator) VALUES (12,1,'SCRIPT_COMPLAINT','SCRIPT','COMPLAINT','投诉处理话术','先致歉并倾听，不辩解；记录投诉内容、时间、涉及环节；承诺 1 个工作日内由主管回复；转交主管并登记投诉。',1,0,'demo-seed') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO message_template (id,hospital_id,code,channel,scene,title,content,is_active,version,creator) VALUES (13,1,'SCRIPT_URGENT','SCRIPT','URGENT','紧急情况话术','若患者描述胸痛、呼吸困难、意识改变等急症表现，立即建议拨打急救电话或前往急诊，不做任何处理建议；随后登记异常并通知责任医生。',1,0,'demo-seed') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO message_template (id,hospital_id,code,channel,scene,title,content,is_active,version,creator) VALUES (14,1,'WECHAT_FOLLOWUP_REMINDER','WECHAT','FOLLOWUP_REMINDER','随访提醒（微信）','{姓名}您好，本周是您的第{N}次随访，请在方便时回复近期血压、体重和用药情况，或告知方便的通话时间。',1,0,'demo-seed') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO sla_config (id,hospital_id,risk_level,first_contact_hours,booking_days,arrival_days,lost_after_attempts,note,version,creator) VALUES (1,1,'CRITICAL',2,1,1,2,'重点关注：2 小时内首触，1 天内预约与到院',0,'demo-seed') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO sla_config (id,hospital_id,risk_level,first_contact_hours,booking_days,arrival_days,lost_after_attempts,note,version,creator) VALUES (2,1,'HIGH',24,3,7,3,'高风险：24 小时首触，3 天预约，7 天到院',0,'demo-seed') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO sla_config (id,hospital_id,risk_level,first_contact_hours,booking_days,arrival_days,lost_after_attempts,note,version,creator) VALUES (3,1,'MEDIUM',72,7,30,3,'中风险：3 天首触',0,'demo-seed') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO sla_config (id,hospital_id,risk_level,first_contact_hours,booking_days,arrival_days,lost_after_attempts,note,version,creator) VALUES (4,1,'LOW',168,30,90,3,'低风险：一周内首触',0,'demo-seed') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO sla_config (id,hospital_id,risk_level,first_contact_hours,booking_days,arrival_days,lost_after_attempts,note,version,creator) VALUES (5,1,'UNKNOWN',168,30,90,3,'未评估按低风险口径',0,'demo-seed') ON DUPLICATE KEY UPDATE id=id;
-- END OPERATIONS LEDGER 1.5
